let
  link = name: url: { inherit name url; };
  short = short: name: url: { name = short; inherit url; };
  dir = name: bookmarks: { inherit name bookmarks; };
in [
  (link "GitHub" "http://github.com")

  (dir "Mail" [
    (link "Gmail" "https://mail.google.com/mail/u/0/#inbox")
    (link "Outlook" "https://outlook.office365.com/mail/")
  ])

  (dir "Nix" [
    (link "Nixpkgs-search" "https://search.nixos.org/packages")
    (link "Home-manager-search" "https://home-manager-options.extranix.com/")
    (link "Nixpkgs Manual" "https://ryantm.github.io/nixpkgs/")
    (link "Nix Lib Manual" "https://teu5us.github.io/nix-lib.html")
    (link "Nix Lib" "https://github.com/NixOS/nixpkgs/tree/master/lib")
    (link "Nix Lib - Strings" "https://github.com/NixOS/nixpkgs/blob/master/lib/strings.nix")
    (link "Nix Lib - Lists" "https://github.com/NixOS/nixpkgs/blob/master/lib/lists.nix")
    (link "Nix Lib - Attrs" "https://github.com/NixOS/nixpkgs/blob/master/lib/attrs.nix")
    (link "Noogle" "https://noogle.dev/")
    (link "NixOS Infra Status" "https://status.nixos.org/")
  ])

  (dir "CTF" [
    (link "Revshells" "https://revshells.com/")
    (link "Exploit Education" "http://exploit.education/")
    (link "Webhook" "https://webhook.site")
    (link "CyberChef" "https://gchq.github.io/CyberChef/")
    (link "Aperisolve" "https://www.aperisolve.com/")
    (link "how2heap" "https://github.com/shellphish/how2heap")
    (link "Heap Search" "https://kissprogramming.com/heap/heap-search")
    (link "CrackStation" "https://crackstation.net/")
    (link "FactorDB" "http://factordb.com/")
    (link "Syscalls" "https://syscalls.w3challs.com/")
    (link "DogBolt" "https://dogbolt.org/")
    (link "HackTricks" "https://book.hacktricks.xyz/")
    (dir "Practise" [
      (link "S2G" "https://s2gctf.ncr.ntnu.no")
      (link "Pico CTF" "https://play.picoctf.org/practice")
      (link "Pwn college" "https://pwn.college/")
      (link "HackTheBox" "https://www.hackthebox.eu")
      (link "Crackmes" "https://crackmes.one")
      (link "Nightmare" "https://guyinatuxedo.github.io/")
    ])
  ])

  (dir "Misc & Tools" [
    (link "ASCIIFlow" "https://asciiflow.com/#/")
    (link "CopyChar" "https://copychar.cc/")
    (link "Device Info" "https://www.deviceinfo.me/")
    (link "Diagrams" "https://app.diagrams.net/")
    (link "FakeMail" "http://www.fakemailgenerator.com/")
    (link "IPLeak" "https://ipleak.net/")
    (link "LaTeX" "https://www.codecogs.com/latex/eqneditor.php")
    (link "ManualsLib" "https://www.manualslib.com/")
    (link "Namechk" "https://namechk.com/")
    (link "NamingSchemes" "https://namingschemes.com/")
    (link "Oryx" "https://configure.ergodox-ez.com/ergodox-ez/layouts/53Pyn/latest/0")
    (link "Pastebin" "https://pastebin.com/u/h7x4")
    (link "PDFescape" "https://www.pdfescape.com/")
    (link "Pixabay" "https://pixabay.com/")
    (link "Pixlr" "https://pixlr.com/e/")
    (link "Privnote" "https://privnote.com/")
    (link "Quiver" "https://q.uiver.app/")
    (short "RD" "RomajiDesu" "http://www.romajidesu.com/")
    (link "waaai" "https://waa.ai/")
    (link "NitroType" "https://www.nitrotype.com/race")
    (link "Duolingo" "https://www.duolingo.com/learn")
    (link "Kanji Garden" "https://kanji.garden/")
    (link "Compiler Explorer" "https://godbolt.org/")
    (link "Readme.so" "https://readme.so/")
    (link "Regexr" "https://regexr.com/")
    (link "Keybr" "https://www.keybr.com/")
    (link "HackerRank" "https://www.hackerrank.com/")
    (link "Project Euler" "https://projecteuler.net/archives")
    (link "FlutterGems" "https://fluttergems.dev/")
    (link "BashOneliners" "http://www.bashoneliners.com/oneliners/popular/")
    (link "PosterDB" "https://theposterdb.com/")
    (link "WikiChip" "https://en.wikichip.org/wiki/WikiChip")
    (link "Gitea - dodsorf.as" "https://git.dodsorf.as/explore/repos")
    (link "Gitea - feal.no" "https://git.feal.no/explore/repos")
    (link "Gitea - glados.no" "https://git.glados.no/explore/repos")
    (link "Chinese Text Project" "https://ctext.org/")
    (link "Just delete me" "https://backgroundchecks.org/justdeleteme/")
    (link "Unicode Resources" "http://xahlee.info/comp/unicode_essays_index.html")
    (link "UTF8 Everywhere" "https://utf8everywhere.org/")
    (link "Polar" "https://getpolarized.io/")
    (link "Everything I Know" "https://wiki.nikitavoloboev.xyz/")
    (link "Aphyr Posts" "https://aphyr.com/")
    (link "Cursed Computer Iceberg" "https://suricrasia.online/iceberg/")
    (link "EPWING dicts" "https://www.japaneselanguagetools.com/docs/other_dics.html")
    (link "Itazuraneko" "https://itazuraneko.neocities.org/#learn")
    (link "妖精ロケット - The Gear Of Seasons" "https://hexe.net/")
    (link "jpdb" "https://jpdb.io/")
  ])

  (dir "orenes" [
    (link "MAAT" "https://maatevolution.betserver.es/home")
    (link "Kolyseo - des01" "https://des.betserver.es/")
    (link "Kolyseo - des02" "https://des02.betserver.es/")
    (link "Aggregators API - des02" "https://des02.betserver.es/")
  ])

  (dir "OTW" [
    (link "Linkedin" "https://www.linkedin.com/jobs/")
    (link "Google Careers" "https://www.google.com/about/careers/applications/dashboard")
    (link "Digitech (swiss talent broker)" "http://www.digitechsearch.com/")
  ])
]
